// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// overlap
NumericVector overlap(IntegerMatrix rankMat);
RcppExport SEXP SuperRanker_overlap(SEXP rankMatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type rankMat(rankMatSEXP);
    __result = Rcpp::wrap(overlap(rankMat));
    return __result;
END_RCPP
}
