// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// overlap
NumericVector overlap(IntegerMatrix rankMat);
RcppExport SEXP SuperRanker_overlap(SEXP rankMatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type rankMat(rankMatSEXP);
    __result = Rcpp::wrap(overlap(rankMat));
    return __result;
END_RCPP
}
// sracpp
NumericVector sracpp(IntegerMatrix rankMat, int maxlength, int B, IntegerVector cens);
RcppExport SEXP SuperRanker_sracpp(SEXP rankMatSEXP, SEXP maxlengthSEXP, SEXP BSEXP, SEXP censSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type rankMat(rankMatSEXP);
    Rcpp::traits::input_parameter< int >::type maxlength(maxlengthSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cens(censSEXP);
    __result = Rcpp::wrap(sracpp(rankMat, maxlength, B, cens));
    return __result;
END_RCPP
}
// sracppfull
NumericVector sracppfull(IntegerMatrix rankMat);
RcppExport SEXP SuperRanker_sracppfull(SEXP rankMatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type rankMat(rankMatSEXP);
    __result = Rcpp::wrap(sracppfull(rankMat));
    return __result;
END_RCPP
}
