# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the overlap between k ranked lists
#' 
#' @description Computes the overlap (number of items present in all k lists divided by the current rank) for each rank in the k lists
#' @param rankMat A matrix with k columns corresponding to the k ranked lists. Elements of each column are integers between 1 and the length of the lists
#' @return A vector of the same length as the rows in rankMat containing the overlap between the lists for each rank
#' @author Claus Ekstrøm <ekstrom@@sund.ku.dk>
#' @export
overlap <- function(rankMat) {
    .Call('SuperRanker_overlap', PACKAGE = 'SuperRanker', rankMat)
}

#' Compute the sequential rank agreement between k ranked lists
#' 
#' @description Computes the sequential rank agreement (number of items present in all k lists divided by the current rank) for each rank in the k lists
#' @param rankMat A matrix with k columns corresponding to the k ranked lists. Elements of each column are integers between 1 and the length of the lists
#' @param maxlength The maximum depth that are needed XXX
#' @param B The number of resamples to use in the presence of censored lists
#' @param cens A vector of integer values that 
#' @return A vector of the same length as the rows in rankMat containing the sequential rank agreement between the lists for each depth
#' @author Claus Ekstrøm <ekstrom@@sund.ku.dk>
#' @export
sracpp <- function(rankMat, maxlength, B, cens) {
    .Call('SuperRanker_sracpp', PACKAGE = 'SuperRanker', rankMat, maxlength, B, cens)
}

#' Compute the sequential rank agreement between k ranked lists
#' 
#' @description Computes the sequential rank agreement (number of items present in all k lists divided by the current rank) for each rank in the k lists
#' @param rankMat A matrix with k columns corresponding to the k ranked lists. Elements of each column are integers between 1 and the length of the lists
#' @return A vector of the same length as the rows in rankMat containing the sequential rank agreement between the lists for each depth
#' @author Claus Ekstrøm <ekstrom@@sund.ku.dk>
#' @export
sracppfull <- function(rankMat) {
    .Call('SuperRanker_sracppfull', PACKAGE = 'SuperRanker', rankMat)
}

